### ISSUE TITLE
Listing map issue

### ISSUE THREAD

**Issue by ajmalhassan** [devpranoy/keralarescue#4]
See this image

https://lh3.googleusercontent.com/-f1b_HqwNUqs/W3gJ5XF87PI/AAAAAAAAAFw/EeYkzRhYWkYbZWoAdSTET4DlBD7gnz0bgCL0BGAYYCw/h286/2018-08-18.png

**Comment by devpranoy** [comment]
Followed it up with Martin and it seems like someone has pasted the location (google maps link) instead of typing in the locatoin
